/* Incremental.c generated by valac 0.27.1, the Vala compiler
 * generated from Incremental.vala, do not modify */

/*
 * Incremental.vala
 *
 * Incremental is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Incremental is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gdk/gdk.h>


#define TYPE_INCREMENTAL (incremental_get_type ())
#define INCREMENTAL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_INCREMENTAL, Incremental))
#define INCREMENTAL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_INCREMENTAL, IncrementalClass))
#define IS_INCREMENTAL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_INCREMENTAL))
#define IS_INCREMENTAL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_INCREMENTAL))
#define INCREMENTAL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_INCREMENTAL, IncrementalClass))

typedef struct _Incremental Incremental;
typedef struct _IncrementalClass IncrementalClass;
typedef struct _IncrementalPrivate IncrementalPrivate;

#define INCREMENTAL_TYPE_SVP (incremental_svp_get_type ())
typedef struct _Incrementalsvp Incrementalsvp;

#define INCREMENTAL_TYPE_COLUMNS (incremental_columns_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))

typedef void (*MyCallBack) (GAction* a, void* user_data);
struct _Incrementalsvp {
	GtkScrolledWindow* scroller;
	GtkViewport* viewport;
};

struct _Incremental {
	GtkApplication parent_instance;
	IncrementalPrivate * priv;
	gchar* AppName;
	gchar* Version;
	GtkApplicationWindow* window;
	GtkGrid* interface_grid;
	GtkTreeView* interface_tree_view;
	GtkHeaderBar* headerbar;
	GtkToggleButton* hide_tree;
	gchar* hide_tree_accelerator;
	gchar* hide_tree_tip;
	GtkButton* append_node;
	gchar* append_node_accelerator;
	gchar* append_node_tip;
	GtkBox* file_box;
	GtkButton* file_new;
	gchar* file_new_accelerator;
	gchar* file_new_tip;
	GtkFileChooserButton* file_select;
	GtkButton* file_export;
	gchar* file_export_accelerator;
	gchar* file_export_tip;
	GtkButton* undo;
	gchar* undo_accelerator;
	gchar* undo_tip;
	GtkButton* redo;
	gchar* redo_accelerator;
	gchar* redo_tip;
	GtkToggleButton* hide_terminal;
	gchar* hide_terminal_accelerator;
	gchar* hide_terminal_tip;
	GtkToggleButton* hide_help;
	gchar* hide_help_accelerator;
	gchar* hide_help_tip;
	Incrementalsvp interface_tree;
	Incrementalsvp interface_document;
	Incrementalsvp interface_help;
	Incrementalsvp interface_terminal;
};

struct _IncrementalClass {
	GtkApplicationClass parent_class;
};

typedef enum  {
	INCREMENTAL_COLUMNS_HEAD,
	INCREMENTAL_COLUMNS_BODY,
	INCREMENTAL_COLUMNS_N_COLUMNS
} IncrementalColumns;

struct _Block1Data {
	int _ref_count_;
	Incremental* self;
	GSimpleAction* toggle_terminal_action;
	GSimpleAction* toggle_help_action;
	GSimpleAction* toggle_tree_action;
};


static gpointer incremental_parent_class = NULL;

GType incremental_get_type (void) G_GNUC_CONST;
GType incremental_svp_get_type (void) G_GNUC_CONST;
Incrementalsvp* incremental_svp_dup (const Incrementalsvp* self);
void incremental_svp_free (Incrementalsvp* self);
void incremental_svp_copy (const Incrementalsvp* self, Incrementalsvp* dest);
void incremental_svp_destroy (Incrementalsvp* self);
enum  {
	INCREMENTAL_DUMMY_PROPERTY
};
GType incremental_columns_get_type (void) G_GNUC_CONST;
Incremental* incremental_new (void);
Incremental* incremental_construct (GType object_type);
static void incremental_real_activate (GApplication* base);
GtkHeaderBar* incremental_create_headerbar (Incremental* self);
void incremental_create_actions (Incremental* self);
GtkGrid* incremental_create_viewer (Incremental* self);
void incremental_toggle_help (Incremental* self);
void incremental_toggle_terminal (Incremental* self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda4_ (Block1Data* _data1_);
void incremental_toggle_visible_prototype (Incremental* self, GtkWidget* widget);
static void ___lambda4__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda5_ (Block1Data* _data1_);
static void ___lambda5__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda6_ (Block1Data* _data1_);
static void ___lambda6__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda7_ (Incremental* self);
static void ___lambda7__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda8_ (Incremental* self);
static void ___lambda8__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda9_ (Incremental* self);
static void ___lambda9__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda10_ (Incremental* self);
static void ___lambda10__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda11_ (Incremental* self);
static void ___lambda11__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
void incremental_toggle_tree (Incremental* self);
gchar* incremental_create_tip_with_accel (Incremental* self, const gchar* tip, const gchar* accel);
void incremental_new_svp (Incremental* self, Incrementalsvp* result);
gint incremental_main (gchar** args, int args_length1);
static void incremental_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


GType incremental_columns_get_type (void) {
	static volatile gsize incremental_columns_type_id__volatile = 0;
	if (g_once_init_enter (&incremental_columns_type_id__volatile)) {
		static const GEnumValue values[] = {{INCREMENTAL_COLUMNS_HEAD, "INCREMENTAL_COLUMNS_HEAD", "head"}, {INCREMENTAL_COLUMNS_BODY, "INCREMENTAL_COLUMNS_BODY", "body"}, {INCREMENTAL_COLUMNS_N_COLUMNS, "INCREMENTAL_COLUMNS_N_COLUMNS", "n-columns"}, {0, NULL, NULL}};
		GType incremental_columns_type_id;
		incremental_columns_type_id = g_enum_register_static ("IncrementalColumns", values);
		g_once_init_leave (&incremental_columns_type_id__volatile, incremental_columns_type_id);
	}
	return incremental_columns_type_id__volatile;
}


Incremental* incremental_construct (GType object_type) {
	Incremental * self = NULL;
	self = (Incremental*) g_object_new (object_type, "application-id", "org.agora.incremental", "flags", G_APPLICATION_FLAGS_NONE, NULL);
	return self;
}


Incremental* incremental_new (void) {
	return incremental_construct (TYPE_INCREMENTAL);
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static void incremental_real_activate (GApplication* base) {
	Incremental * self;
	GtkApplicationWindow* window = NULL;
	GtkApplicationWindow* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	GtkHeaderBar* _tmp7_ = NULL;
	GtkHeaderBar* _tmp8_ = NULL;
	GtkGrid* _tmp9_ = NULL;
	GtkGrid* _tmp10_ = NULL;
	self = (Incremental*) base;
	_tmp0_ = (GtkApplicationWindow*) gtk_application_window_new ((GtkApplication*) self);
	g_object_ref_sink (_tmp0_);
	window = _tmp0_;
	gtk_window_resize ((GtkWindow*) window, 800, 600);
	_tmp1_ = self->AppName;
	_tmp2_ = string_to_string (_tmp1_);
	_tmp3_ = self->Version;
	_tmp4_ = string_to_string (_tmp3_);
	_tmp5_ = g_strconcat (_tmp2_, " ", _tmp4_, NULL);
	_tmp6_ = _tmp5_;
	gtk_window_set_title ((GtkWindow*) window, _tmp6_);
	_g_free0 (_tmp6_);
	gtk_window_set_position ((GtkWindow*) window, GTK_WIN_POS_CENTER);
	_tmp7_ = incremental_create_headerbar (self);
	_tmp8_ = _tmp7_;
	gtk_window_set_titlebar ((GtkWindow*) window, (GtkWidget*) _tmp8_);
	_g_object_unref0 (_tmp8_);
	incremental_create_actions (self);
	_tmp9_ = incremental_create_viewer (self);
	_g_object_unref0 (self->interface_grid);
	self->interface_grid = _tmp9_;
	_tmp10_ = self->interface_grid;
	gtk_container_add ((GtkContainer*) window, (GtkWidget*) _tmp10_);
	gtk_widget_show_all ((GtkWidget*) window);
	incremental_toggle_help (self);
	incremental_toggle_terminal (self);
	_g_object_unref0 (window);
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		Incremental* self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->toggle_tree_action);
		_g_object_unref0 (_data1_->toggle_help_action);
		_g_object_unref0 (_data1_->toggle_terminal_action);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}


static void __lambda4_ (Block1Data* _data1_) {
	Incremental* self;
	GVariant* state = NULL;
	GVariant* _tmp0_ = NULL;
	gboolean b = FALSE;
	gboolean _tmp1_ = FALSE;
	GVariant* _tmp2_ = NULL;
	GVariant* _tmp3_ = NULL;
	Incrementalsvp _tmp4_ = {0};
	GtkScrolledWindow* _tmp5_ = NULL;
	self = _data1_->self;
	g_application_hold ((GApplication*) self);
	_tmp0_ = g_action_get_state ((GAction*) _data1_->toggle_terminal_action);
	state = _tmp0_;
	_tmp1_ = g_variant_get_boolean (state);
	b = _tmp1_;
	_tmp2_ = g_variant_new_boolean (!b);
	g_variant_ref_sink (_tmp2_);
	_tmp3_ = _tmp2_;
	g_simple_action_set_state (_data1_->toggle_terminal_action, _tmp3_);
	_g_variant_unref0 (_tmp3_);
	_tmp4_ = self->interface_terminal;
	_tmp5_ = _tmp4_.scroller;
	incremental_toggle_visible_prototype (self, (GtkWidget*) _tmp5_);
	g_application_release ((GApplication*) self);
	_g_variant_unref0 (state);
}


static void ___lambda4__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda4_ (self);
}


static void __lambda5_ (Block1Data* _data1_) {
	Incremental* self;
	GVariant* state = NULL;
	GVariant* _tmp0_ = NULL;
	gboolean b = FALSE;
	gboolean _tmp1_ = FALSE;
	GVariant* _tmp2_ = NULL;
	GVariant* _tmp3_ = NULL;
	Incrementalsvp _tmp4_ = {0};
	GtkScrolledWindow* _tmp5_ = NULL;
	self = _data1_->self;
	g_application_hold ((GApplication*) self);
	_tmp0_ = g_action_get_state ((GAction*) _data1_->toggle_help_action);
	state = _tmp0_;
	_tmp1_ = g_variant_get_boolean (state);
	b = _tmp1_;
	_tmp2_ = g_variant_new_boolean (!b);
	g_variant_ref_sink (_tmp2_);
	_tmp3_ = _tmp2_;
	g_simple_action_set_state (_data1_->toggle_help_action, _tmp3_);
	_g_variant_unref0 (_tmp3_);
	_tmp4_ = self->interface_help;
	_tmp5_ = _tmp4_.scroller;
	incremental_toggle_visible_prototype (self, (GtkWidget*) _tmp5_);
	g_application_release ((GApplication*) self);
	_g_variant_unref0 (state);
}


static void ___lambda5__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda5_ (self);
}


static void __lambda6_ (Block1Data* _data1_) {
	Incremental* self;
	GVariant* state = NULL;
	GVariant* _tmp0_ = NULL;
	gboolean b = FALSE;
	gboolean _tmp1_ = FALSE;
	GVariant* _tmp2_ = NULL;
	GVariant* _tmp3_ = NULL;
	Incrementalsvp _tmp4_ = {0};
	GtkScrolledWindow* _tmp5_ = NULL;
	self = _data1_->self;
	g_application_hold ((GApplication*) self);
	_tmp0_ = g_action_get_state ((GAction*) _data1_->toggle_tree_action);
	state = _tmp0_;
	_tmp1_ = g_variant_get_boolean (state);
	b = _tmp1_;
	_tmp2_ = g_variant_new_boolean (!b);
	g_variant_ref_sink (_tmp2_);
	_tmp3_ = _tmp2_;
	g_simple_action_set_state (_data1_->toggle_tree_action, _tmp3_);
	_g_variant_unref0 (_tmp3_);
	_tmp4_ = self->interface_tree;
	_tmp5_ = _tmp4_.scroller;
	incremental_toggle_visible_prototype (self, (GtkWidget*) _tmp5_);
	g_application_release ((GApplication*) self);
	_g_variant_unref0 (state);
}


static void ___lambda6__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda6_ (self);
}


static void __lambda7_ (Incremental* self) {
	FILE* _tmp0_ = NULL;
	g_application_hold ((GApplication*) self);
	_tmp0_ = stderr;
	fprintf (_tmp0_, "user clicked undo or pressed <ctrl>z\n");
	g_application_release ((GApplication*) self);
}


static void ___lambda7__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda7_ ((Incremental*) self);
}


static void __lambda8_ (Incremental* self) {
	FILE* _tmp0_ = NULL;
	g_application_hold ((GApplication*) self);
	_tmp0_ = stderr;
	fprintf (_tmp0_, "user clicked redo or pressed <ctrl>y\n");
	g_application_release ((GApplication*) self);
}


static void ___lambda8__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda8_ ((Incremental*) self);
}


static void __lambda9_ (Incremental* self) {
	FILE* _tmp0_ = NULL;
	g_application_hold ((GApplication*) self);
	_tmp0_ = stderr;
	fprintf (_tmp0_, "user clicked append node or pressed <ctrl><shift>n\n");
	g_application_release ((GApplication*) self);
}


static void ___lambda9__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda9_ ((Incremental*) self);
}


static void __lambda10_ (Incremental* self) {
	FILE* _tmp0_ = NULL;
	g_application_hold ((GApplication*) self);
	_tmp0_ = stderr;
	fprintf (_tmp0_, "user clicked new or pressed <ctrl>n\n");
	g_application_release ((GApplication*) self);
}


static void ___lambda10__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda10_ ((Incremental*) self);
}


static void __lambda11_ (Incremental* self) {
	FILE* _tmp0_ = NULL;
	g_application_hold ((GApplication*) self);
	_tmp0_ = stderr;
	fprintf (_tmp0_, "user clicked export or pressed <ctrl>e\n");
	g_application_release ((GApplication*) self);
}


static void ___lambda11__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda11_ ((Incremental*) self);
}


void incremental_create_actions (Incremental* self) {
	Block1Data* _data1_;
	GVariant* _tmp0_ = NULL;
	GVariant* _tmp1_ = NULL;
	GSimpleAction* _tmp2_ = NULL;
	GSimpleAction* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar** _tmp5_ = NULL;
	gchar** _tmp6_ = NULL;
	gint _tmp6__length1 = 0;
	GVariant* _tmp7_ = NULL;
	GVariant* _tmp8_ = NULL;
	GSimpleAction* _tmp9_ = NULL;
	GSimpleAction* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar** _tmp12_ = NULL;
	gchar** _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	GVariant* _tmp14_ = NULL;
	GVariant* _tmp15_ = NULL;
	GSimpleAction* _tmp16_ = NULL;
	GSimpleAction* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar** _tmp19_ = NULL;
	gchar** _tmp20_ = NULL;
	gint _tmp20__length1 = 0;
	GSimpleAction* undo_action = NULL;
	GSimpleAction* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gchar** _tmp24_ = NULL;
	gchar** _tmp25_ = NULL;
	gint _tmp25__length1 = 0;
	GSimpleAction* redo_action = NULL;
	GSimpleAction* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	gchar** _tmp28_ = NULL;
	gchar** _tmp29_ = NULL;
	gint _tmp29__length1 = 0;
	GSimpleAction* append_action = NULL;
	GSimpleAction* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	gchar** _tmp32_ = NULL;
	gchar** _tmp33_ = NULL;
	gint _tmp33__length1 = 0;
	GSimpleAction* new_action = NULL;
	GSimpleAction* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	gchar** _tmp36_ = NULL;
	gchar** _tmp37_ = NULL;
	gint _tmp37__length1 = 0;
	GSimpleAction* export_action = NULL;
	GSimpleAction* _tmp38_ = NULL;
	gchar* _tmp39_ = NULL;
	gchar** _tmp40_ = NULL;
	gchar** _tmp41_ = NULL;
	gint _tmp41__length1 = 0;
	g_return_if_fail (self != NULL);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_tmp0_ = g_variant_new_boolean (FALSE);
	g_variant_ref_sink (_tmp0_);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_simple_action_new_stateful ("toggle-terminal", NULL, _tmp1_);
	_tmp3_ = _tmp2_;
	_g_variant_unref0 (_tmp1_);
	_data1_->toggle_terminal_action = _tmp3_;
	g_signal_connect_data (_data1_->toggle_terminal_action, "activate", (GCallback) ___lambda4__g_simple_action_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) _data1_->toggle_terminal_action);
	_tmp4_ = g_strdup ("F12");
	_tmp5_ = g_new0 (gchar*, 1 + 1);
	_tmp5_[0] = _tmp4_;
	_tmp6_ = _tmp5_;
	_tmp6__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.toggle-terminal", _tmp6_);
	_tmp6_ = (_vala_array_free (_tmp6_, _tmp6__length1, (GDestroyNotify) g_free), NULL);
	_tmp7_ = g_variant_new_boolean (FALSE);
	g_variant_ref_sink (_tmp7_);
	_tmp8_ = _tmp7_;
	_tmp9_ = g_simple_action_new_stateful ("toggle-help", NULL, _tmp8_);
	_tmp10_ = _tmp9_;
	_g_variant_unref0 (_tmp8_);
	_data1_->toggle_help_action = _tmp10_;
	g_signal_connect_data (_data1_->toggle_help_action, "activate", (GCallback) ___lambda5__g_simple_action_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) _data1_->toggle_help_action);
	_tmp11_ = g_strdup ("F1");
	_tmp12_ = g_new0 (gchar*, 1 + 1);
	_tmp12_[0] = _tmp11_;
	_tmp13_ = _tmp12_;
	_tmp13__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.toggle-help", _tmp13_);
	_tmp13_ = (_vala_array_free (_tmp13_, _tmp13__length1, (GDestroyNotify) g_free), NULL);
	_tmp14_ = g_variant_new_boolean (TRUE);
	g_variant_ref_sink (_tmp14_);
	_tmp15_ = _tmp14_;
	_tmp16_ = g_simple_action_new_stateful ("toggle-tree", NULL, _tmp15_);
	_tmp17_ = _tmp16_;
	_g_variant_unref0 (_tmp15_);
	_data1_->toggle_tree_action = _tmp17_;
	g_signal_connect_data (_data1_->toggle_tree_action, "activate", (GCallback) ___lambda6__g_simple_action_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) _data1_->toggle_tree_action);
	_tmp18_ = g_strdup ("F10");
	_tmp19_ = g_new0 (gchar*, 1 + 1);
	_tmp19_[0] = _tmp18_;
	_tmp20_ = _tmp19_;
	_tmp20__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.toggle-tree", _tmp20_);
	_tmp20_ = (_vala_array_free (_tmp20_, _tmp20__length1, (GDestroyNotify) g_free), NULL);
	_tmp21_ = g_simple_action_new ("undo", NULL);
	undo_action = _tmp21_;
	g_signal_connect_object (undo_action, "activate", (GCallback) ___lambda7__g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) undo_action);
	_tmp22_ = self->undo_accelerator;
	_tmp23_ = g_strdup (_tmp22_);
	_tmp24_ = g_new0 (gchar*, 1 + 1);
	_tmp24_[0] = _tmp23_;
	_tmp25_ = _tmp24_;
	_tmp25__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.undo", _tmp25_);
	_tmp25_ = (_vala_array_free (_tmp25_, _tmp25__length1, (GDestroyNotify) g_free), NULL);
	_tmp26_ = g_simple_action_new ("redo", NULL);
	redo_action = _tmp26_;
	g_signal_connect_object (redo_action, "activate", (GCallback) ___lambda8__g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) redo_action);
	_tmp27_ = g_strdup ("<ctrl>y");
	_tmp28_ = g_new0 (gchar*, 1 + 1);
	_tmp28_[0] = _tmp27_;
	_tmp29_ = _tmp28_;
	_tmp29__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.redo", _tmp29_);
	_tmp29_ = (_vala_array_free (_tmp29_, _tmp29__length1, (GDestroyNotify) g_free), NULL);
	_tmp30_ = g_simple_action_new ("append", NULL);
	append_action = _tmp30_;
	g_signal_connect_object (append_action, "activate", (GCallback) ___lambda9__g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) append_action);
	_tmp31_ = g_strdup ("<ctrl><shift>n");
	_tmp32_ = g_new0 (gchar*, 1 + 1);
	_tmp32_[0] = _tmp31_;
	_tmp33_ = _tmp32_;
	_tmp33__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.append", _tmp33_);
	_tmp33_ = (_vala_array_free (_tmp33_, _tmp33__length1, (GDestroyNotify) g_free), NULL);
	_tmp34_ = g_simple_action_new ("new", NULL);
	new_action = _tmp34_;
	g_signal_connect_object (new_action, "activate", (GCallback) ___lambda10__g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) new_action);
	_tmp35_ = g_strdup ("<ctrl>n");
	_tmp36_ = g_new0 (gchar*, 1 + 1);
	_tmp36_[0] = _tmp35_;
	_tmp37_ = _tmp36_;
	_tmp37__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.new", _tmp37_);
	_tmp37_ = (_vala_array_free (_tmp37_, _tmp37__length1, (GDestroyNotify) g_free), NULL);
	_tmp38_ = g_simple_action_new ("export", NULL);
	export_action = _tmp38_;
	g_signal_connect_object (export_action, "activate", (GCallback) ___lambda11__g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) export_action);
	_tmp39_ = g_strdup ("<ctrl>e");
	_tmp40_ = g_new0 (gchar*, 1 + 1);
	_tmp40_[0] = _tmp39_;
	_tmp41_ = _tmp40_;
	_tmp41__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.export", _tmp41_);
	_tmp41_ = (_vala_array_free (_tmp41_, _tmp41__length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (export_action);
	_g_object_unref0 (new_action);
	_g_object_unref0 (append_action);
	_g_object_unref0 (redo_action);
	_g_object_unref0 (undo_action);
	block1_data_unref (_data1_);
	_data1_ = NULL;
}


void incremental_toggle_visible_prototype (Incremental* self, GtkWidget* widget) {
	GtkWidget* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	_tmp0_ = widget;
	_tmp1_ = gtk_widget_get_visible (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		GtkWidget* _tmp3_ = NULL;
		_tmp3_ = widget;
		gtk_widget_set_visible (_tmp3_, FALSE);
	} else {
		GtkWidget* _tmp4_ = NULL;
		_tmp4_ = widget;
		gtk_widget_set_visible (_tmp4_, TRUE);
	}
}


void incremental_toggle_tree (Incremental* self) {
	g_return_if_fail (self != NULL);
}


void incremental_toggle_help (Incremental* self) {
	Incrementalsvp _tmp0_ = {0};
	GtkScrolledWindow* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->interface_help;
	_tmp1_ = _tmp0_.scroller;
	incremental_toggle_visible_prototype (self, (GtkWidget*) _tmp1_);
}


void incremental_toggle_terminal (Incremental* self) {
	Incrementalsvp _tmp0_ = {0};
	GtkScrolledWindow* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->interface_terminal;
	_tmp1_ = _tmp0_.scroller;
	incremental_toggle_visible_prototype (self, (GtkWidget*) _tmp1_);
}


gchar* incremental_create_tip_with_accel (Incremental* self, const gchar* tip, const gchar* accel) {
	gchar* result = NULL;
	gchar* accel_tip = NULL;
	guint accel_key = 0U;
	GdkModifierType accel_mods = 0;
	const gchar* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	GdkModifierType _tmp2_ = 0;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (tip != NULL, NULL);
	g_return_val_if_fail (accel != NULL, NULL);
	_tmp0_ = accel;
	gtk_accelerator_parse (_tmp0_, &_tmp1_, &_tmp2_);
	accel_key = _tmp1_;
	accel_mods = _tmp2_;
	_tmp3_ = gtk_accelerator_get_label (accel_key, accel_mods);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat ("\n<b>(", _tmp4_, NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_strconcat (_tmp6_, ")</b>", NULL);
	_g_free0 (accel_tip);
	accel_tip = _tmp7_;
	_g_free0 (_tmp6_);
	_g_free0 (_tmp4_);
	_tmp8_ = tip;
	_tmp9_ = g_strconcat (_tmp8_, accel_tip, NULL);
	result = _tmp9_;
	_g_free0 (accel_tip);
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GtkHeaderBar* incremental_create_headerbar (Incremental* self) {
	GtkHeaderBar* result = NULL;
	GtkHeaderBar* _tmp0_ = NULL;
	GtkHeaderBar* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	GtkButton* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	GtkButton* _tmp8_ = NULL;
	GtkHeaderBar* _tmp9_ = NULL;
	GtkButton* _tmp10_ = NULL;
	GtkButton* _tmp11_ = NULL;
	GtkButton* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	GtkButton* _tmp17_ = NULL;
	GtkHeaderBar* _tmp18_ = NULL;
	GtkButton* _tmp19_ = NULL;
	GtkButton* _tmp20_ = NULL;
	GtkButton* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	GtkButton* _tmp26_ = NULL;
	GtkHeaderBar* _tmp27_ = NULL;
	GtkButton* _tmp28_ = NULL;
	GtkBox* _tmp29_ = NULL;
	GtkButton* _tmp30_ = NULL;
	GtkButton* _tmp31_ = NULL;
	const gchar* _tmp32_ = NULL;
	const gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	GtkButton* _tmp36_ = NULL;
	GtkFileChooserButton* _tmp37_ = NULL;
	GtkFileChooserButton* _tmp38_ = NULL;
	GtkButton* _tmp39_ = NULL;
	GtkButton* _tmp40_ = NULL;
	const gchar* _tmp41_ = NULL;
	const gchar* _tmp42_ = NULL;
	gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	GtkButton* _tmp45_ = NULL;
	GtkBox* _tmp46_ = NULL;
	GtkButton* _tmp47_ = NULL;
	GtkBox* _tmp48_ = NULL;
	GtkFileChooserButton* _tmp49_ = NULL;
	GtkBox* _tmp50_ = NULL;
	GtkButton* _tmp51_ = NULL;
	GtkHeaderBar* _tmp52_ = NULL;
	GtkBox* _tmp53_ = NULL;
	GtkToggleButton* _tmp54_ = NULL;
	GtkToggleButton* _tmp55_ = NULL;
	GtkImage* _tmp56_ = NULL;
	GtkImage* _tmp57_ = NULL;
	GtkToggleButton* _tmp58_ = NULL;
	const gchar* _tmp59_ = NULL;
	const gchar* _tmp60_ = NULL;
	gchar* _tmp61_ = NULL;
	gchar* _tmp62_ = NULL;
	GtkToggleButton* _tmp63_ = NULL;
	GtkHeaderBar* _tmp64_ = NULL;
	GtkToggleButton* _tmp65_ = NULL;
	GtkToggleButton* _tmp66_ = NULL;
	GtkToggleButton* _tmp67_ = NULL;
	GtkImage* _tmp68_ = NULL;
	GtkImage* _tmp69_ = NULL;
	GtkToggleButton* _tmp70_ = NULL;
	const gchar* _tmp71_ = NULL;
	const gchar* _tmp72_ = NULL;
	gchar* _tmp73_ = NULL;
	gchar* _tmp74_ = NULL;
	GtkToggleButton* _tmp75_ = NULL;
	GtkHeaderBar* _tmp76_ = NULL;
	GtkToggleButton* _tmp77_ = NULL;
	GtkToggleButton* _tmp78_ = NULL;
	GtkToggleButton* _tmp79_ = NULL;
	GtkImage* _tmp80_ = NULL;
	GtkImage* _tmp81_ = NULL;
	GtkToggleButton* _tmp82_ = NULL;
	const gchar* _tmp83_ = NULL;
	const gchar* _tmp84_ = NULL;
	gchar* _tmp85_ = NULL;
	gchar* _tmp86_ = NULL;
	GtkToggleButton* _tmp87_ = NULL;
	GtkToggleButton* _tmp88_ = NULL;
	GtkHeaderBar* _tmp89_ = NULL;
	GtkToggleButton* _tmp90_ = NULL;
	GtkHeaderBar* _tmp91_ = NULL;
	GtkHeaderBar* _tmp92_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = (GtkHeaderBar*) gtk_header_bar_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->headerbar);
	self->headerbar = _tmp0_;
	_tmp1_ = self->headerbar;
	gtk_header_bar_set_show_close_button (_tmp1_, TRUE);
	_tmp2_ = (GtkButton*) gtk_button_new_from_icon_name ("list-add-symbolic", GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->append_node);
	self->append_node = _tmp2_;
	_tmp3_ = self->append_node;
	_tmp4_ = self->append_node_tip;
	_tmp5_ = self->append_node_accelerator;
	_tmp6_ = incremental_create_tip_with_accel (self, _tmp4_, _tmp5_);
	_tmp7_ = _tmp6_;
	gtk_widget_set_tooltip_markup ((GtkWidget*) _tmp3_, _tmp7_);
	_g_free0 (_tmp7_);
	_tmp8_ = self->append_node;
	gtk_actionable_set_action_name ((GtkActionable*) _tmp8_, "app.append");
	_tmp9_ = self->headerbar;
	_tmp10_ = self->append_node;
	gtk_header_bar_pack_start (_tmp9_, (GtkWidget*) _tmp10_);
	_tmp11_ = (GtkButton*) gtk_button_new_from_icon_name ("edit-undo-symbolic", GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp11_);
	_g_object_unref0 (self->undo);
	self->undo = _tmp11_;
	_tmp12_ = self->undo;
	_tmp13_ = self->undo_tip;
	_tmp14_ = self->undo_accelerator;
	_tmp15_ = incremental_create_tip_with_accel (self, _tmp13_, _tmp14_);
	_tmp16_ = _tmp15_;
	gtk_widget_set_tooltip_markup ((GtkWidget*) _tmp12_, _tmp16_);
	_g_free0 (_tmp16_);
	_tmp17_ = self->undo;
	gtk_actionable_set_action_name ((GtkActionable*) _tmp17_, "app.undo");
	_tmp18_ = self->headerbar;
	_tmp19_ = self->undo;
	gtk_header_bar_pack_start (_tmp18_, (GtkWidget*) _tmp19_);
	_tmp20_ = (GtkButton*) gtk_button_new_from_icon_name ("edit-redo-symbolic", GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp20_);
	_g_object_unref0 (self->redo);
	self->redo = _tmp20_;
	_tmp21_ = self->redo;
	_tmp22_ = self->redo_tip;
	_tmp23_ = self->redo_accelerator;
	_tmp24_ = incremental_create_tip_with_accel (self, _tmp22_, _tmp23_);
	_tmp25_ = _tmp24_;
	gtk_widget_set_tooltip_markup ((GtkWidget*) _tmp21_, _tmp25_);
	_g_free0 (_tmp25_);
	_tmp26_ = self->redo;
	gtk_actionable_set_action_name ((GtkActionable*) _tmp26_, "app.redo");
	_tmp27_ = self->headerbar;
	_tmp28_ = self->redo;
	gtk_header_bar_pack_start (_tmp27_, (GtkWidget*) _tmp28_);
	_tmp29_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp29_);
	_g_object_unref0 (self->file_box);
	self->file_box = _tmp29_;
	_tmp30_ = (GtkButton*) gtk_button_new_from_icon_name ("document-new-symbolic", GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp30_);
	_g_object_unref0 (self->file_new);
	self->file_new = _tmp30_;
	_tmp31_ = self->file_new;
	_tmp32_ = self->file_new_tip;
	_tmp33_ = self->file_new_accelerator;
	_tmp34_ = incremental_create_tip_with_accel (self, _tmp32_, _tmp33_);
	_tmp35_ = _tmp34_;
	gtk_widget_set_tooltip_markup ((GtkWidget*) _tmp31_, _tmp35_);
	_g_free0 (_tmp35_);
	_tmp36_ = self->file_new;
	gtk_actionable_set_action_name ((GtkActionable*) _tmp36_, "app.new");
	_tmp37_ = (GtkFileChooserButton*) gtk_file_chooser_button_new ("No file open", GTK_FILE_CHOOSER_ACTION_OPEN);
	g_object_ref_sink (_tmp37_);
	_g_object_unref0 (self->file_select);
	self->file_select = _tmp37_;
	_tmp38_ = self->file_select;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp38_, "Open document");
	_tmp39_ = (GtkButton*) gtk_button_new_from_icon_name ("document-export-symbolic", GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp39_);
	_g_object_unref0 (self->file_export);
	self->file_export = _tmp39_;
	_tmp40_ = self->file_export;
	_tmp41_ = self->file_export_tip;
	_tmp42_ = self->file_export_accelerator;
	_tmp43_ = incremental_create_tip_with_accel (self, _tmp41_, _tmp42_);
	_tmp44_ = _tmp43_;
	gtk_widget_set_tooltip_markup ((GtkWidget*) _tmp40_, _tmp44_);
	_g_free0 (_tmp44_);
	_tmp45_ = self->file_export;
	gtk_actionable_set_action_name ((GtkActionable*) _tmp45_, "app.export");
	_tmp46_ = self->file_box;
	_tmp47_ = self->file_new;
	gtk_container_add ((GtkContainer*) _tmp46_, (GtkWidget*) _tmp47_);
	_tmp48_ = self->file_box;
	_tmp49_ = self->file_select;
	gtk_container_add ((GtkContainer*) _tmp48_, (GtkWidget*) _tmp49_);
	_tmp50_ = self->file_box;
	_tmp51_ = self->file_export;
	gtk_container_add ((GtkContainer*) _tmp50_, (GtkWidget*) _tmp51_);
	_tmp52_ = self->headerbar;
	_tmp53_ = self->file_box;
	gtk_header_bar_set_custom_title (_tmp52_, (GtkWidget*) _tmp53_);
	_tmp54_ = (GtkToggleButton*) gtk_toggle_button_new ();
	g_object_ref_sink (_tmp54_);
	_g_object_unref0 (self->hide_help);
	self->hide_help = _tmp54_;
	_tmp55_ = self->hide_help;
	_tmp56_ = (GtkImage*) gtk_image_new_from_icon_name ("help-browser-symbolic", GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp56_);
	_tmp57_ = _tmp56_;
	gtk_button_set_image ((GtkButton*) _tmp55_, (GtkWidget*) _tmp57_);
	_g_object_unref0 (_tmp57_);
	_tmp58_ = self->hide_help;
	_tmp59_ = self->hide_help_tip;
	_tmp60_ = self->hide_help_accelerator;
	_tmp61_ = incremental_create_tip_with_accel (self, _tmp59_, _tmp60_);
	_tmp62_ = _tmp61_;
	gtk_widget_set_tooltip_markup ((GtkWidget*) _tmp58_, _tmp62_);
	_g_free0 (_tmp62_);
	_tmp63_ = self->hide_help;
	gtk_actionable_set_action_name ((GtkActionable*) _tmp63_, "app.toggle-help");
	_tmp64_ = self->headerbar;
	_tmp65_ = self->hide_help;
	gtk_header_bar_pack_end (_tmp64_, (GtkWidget*) _tmp65_);
	_tmp66_ = (GtkToggleButton*) gtk_toggle_button_new ();
	g_object_ref_sink (_tmp66_);
	_g_object_unref0 (self->hide_terminal);
	self->hide_terminal = _tmp66_;
	_tmp67_ = self->hide_terminal;
	_tmp68_ = (GtkImage*) gtk_image_new_from_icon_name ("utilities-terminal-symbolic", GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp68_);
	_tmp69_ = _tmp68_;
	gtk_button_set_image ((GtkButton*) _tmp67_, (GtkWidget*) _tmp69_);
	_g_object_unref0 (_tmp69_);
	_tmp70_ = self->hide_terminal;
	_tmp71_ = self->hide_terminal_tip;
	_tmp72_ = self->hide_terminal_accelerator;
	_tmp73_ = incremental_create_tip_with_accel (self, _tmp71_, _tmp72_);
	_tmp74_ = _tmp73_;
	gtk_widget_set_tooltip_markup ((GtkWidget*) _tmp70_, _tmp74_);
	_g_free0 (_tmp74_);
	_tmp75_ = self->hide_terminal;
	gtk_actionable_set_action_name ((GtkActionable*) _tmp75_, "app.toggle-terminal");
	_tmp76_ = self->headerbar;
	_tmp77_ = self->hide_terminal;
	gtk_header_bar_pack_end (_tmp76_, (GtkWidget*) _tmp77_);
	_tmp78_ = (GtkToggleButton*) gtk_toggle_button_new ();
	g_object_ref_sink (_tmp78_);
	_g_object_unref0 (self->hide_tree);
	self->hide_tree = _tmp78_;
	_tmp79_ = self->hide_tree;
	_tmp80_ = (GtkImage*) gtk_image_new_from_icon_name ("pane-hide-symbolic", GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp80_);
	_tmp81_ = _tmp80_;
	gtk_button_set_image ((GtkButton*) _tmp79_, (GtkWidget*) _tmp81_);
	_g_object_unref0 (_tmp81_);
	_tmp82_ = self->hide_tree;
	_tmp83_ = self->hide_tree_tip;
	_tmp84_ = self->hide_tree_accelerator;
	_tmp85_ = incremental_create_tip_with_accel (self, _tmp83_, _tmp84_);
	_tmp86_ = _tmp85_;
	gtk_widget_set_tooltip_markup ((GtkWidget*) _tmp82_, _tmp86_);
	_g_free0 (_tmp86_);
	_tmp87_ = self->hide_tree;
	gtk_toggle_button_set_active (_tmp87_, TRUE);
	_tmp88_ = self->hide_tree;
	gtk_actionable_set_action_name ((GtkActionable*) _tmp88_, "app.toggle-tree");
	_tmp89_ = self->headerbar;
	_tmp90_ = self->hide_tree;
	gtk_header_bar_pack_end (_tmp89_, (GtkWidget*) _tmp90_);
	_tmp91_ = self->headerbar;
	_tmp92_ = _g_object_ref0 (_tmp91_);
	result = _tmp92_;
	return result;
}


void incremental_new_svp (Incremental* self, Incrementalsvp* result) {
	Incrementalsvp temp = {0};
	GtkScrolledWindow* _tmp0_ = NULL;
	GtkViewport* _tmp1_ = NULL;
	Incrementalsvp _tmp2_ = {0};
	Incrementalsvp _tmp3_ = {0};
	GtkScrolledWindow* _tmp4_ = NULL;
	Incrementalsvp _tmp5_ = {0};
	GtkViewport* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp0_);
	_tmp1_ = (GtkViewport*) gtk_viewport_new (NULL, NULL);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (_tmp2_.scroller);
	_tmp2_.scroller = _tmp0_;
	_g_object_unref0 (_tmp2_.viewport);
	_tmp2_.viewport = _tmp1_;
	temp = _tmp2_;
	_tmp3_ = temp;
	_tmp4_ = _tmp3_.scroller;
	_tmp5_ = temp;
	_tmp6_ = _tmp5_.viewport;
	gtk_container_add ((GtkContainer*) _tmp4_, (GtkWidget*) _tmp6_);
	*result = temp;
	return;
}


GtkGrid* incremental_create_viewer (Incremental* self) {
	GtkGrid* result = NULL;
	GtkGrid* _tmp0_ = NULL;
	Incrementalsvp _tmp1_ = {0};
	Incrementalsvp _tmp2_ = {0};
	Incrementalsvp _tmp3_ = {0};
	Incrementalsvp _tmp4_ = {0};
	GtkGrid* _tmp5_ = NULL;
	Incrementalsvp _tmp6_ = {0};
	GtkScrolledWindow* _tmp7_ = NULL;
	GtkGrid* _tmp8_ = NULL;
	Incrementalsvp _tmp9_ = {0};
	GtkScrolledWindow* _tmp10_ = NULL;
	GtkGrid* _tmp11_ = NULL;
	Incrementalsvp _tmp12_ = {0};
	GtkScrolledWindow* _tmp13_ = NULL;
	GtkGrid* _tmp14_ = NULL;
	Incrementalsvp _tmp15_ = {0};
	GtkScrolledWindow* _tmp16_ = NULL;
	GtkFrame* temp_tree = NULL;
	GtkFrame* _tmp17_ = NULL;
	GtkFrame* temp_document = NULL;
	GtkFrame* _tmp18_ = NULL;
	GtkFrame* temp_terminal = NULL;
	GtkFrame* _tmp19_ = NULL;
	GtkFrame* temp_help = NULL;
	GtkFrame* _tmp20_ = NULL;
	Incrementalsvp _tmp21_ = {0};
	GtkViewport* _tmp22_ = NULL;
	Incrementalsvp _tmp23_ = {0};
	GtkViewport* _tmp24_ = NULL;
	Incrementalsvp _tmp25_ = {0};
	GtkViewport* _tmp26_ = NULL;
	Incrementalsvp _tmp27_ = {0};
	GtkViewport* _tmp28_ = NULL;
	GtkGrid* _tmp29_ = NULL;
	GtkGrid* _tmp30_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->interface_grid);
	self->interface_grid = _tmp0_;
	incremental_new_svp (self, &_tmp1_);
	incremental_svp_destroy (&self->interface_tree);
	self->interface_tree = _tmp1_;
	incremental_new_svp (self, &_tmp2_);
	incremental_svp_destroy (&self->interface_document);
	self->interface_document = _tmp2_;
	incremental_new_svp (self, &_tmp3_);
	incremental_svp_destroy (&self->interface_terminal);
	self->interface_terminal = _tmp3_;
	incremental_new_svp (self, &_tmp4_);
	incremental_svp_destroy (&self->interface_help);
	self->interface_help = _tmp4_;
	_tmp5_ = self->interface_grid;
	_tmp6_ = self->interface_tree;
	_tmp7_ = _tmp6_.scroller;
	gtk_grid_attach (_tmp5_, (GtkWidget*) _tmp7_, 0, 0, 1, 1);
	_tmp8_ = self->interface_grid;
	_tmp9_ = self->interface_document;
	_tmp10_ = _tmp9_.scroller;
	gtk_grid_attach (_tmp8_, (GtkWidget*) _tmp10_, 1, 0, 1, 1);
	_tmp11_ = self->interface_grid;
	_tmp12_ = self->interface_help;
	_tmp13_ = _tmp12_.scroller;
	gtk_grid_attach (_tmp11_, (GtkWidget*) _tmp13_, 2, 0, 1, 1);
	_tmp14_ = self->interface_grid;
	_tmp15_ = self->interface_terminal;
	_tmp16_ = _tmp15_.scroller;
	gtk_grid_attach (_tmp14_, (GtkWidget*) _tmp16_, 0, 1, 3, 1);
	_tmp17_ = (GtkFrame*) gtk_frame_new ("tree");
	g_object_ref_sink (_tmp17_);
	temp_tree = _tmp17_;
	g_object_set ((GtkWidget*) temp_tree, "expand", TRUE, NULL);
	_tmp18_ = (GtkFrame*) gtk_frame_new ("document");
	g_object_ref_sink (_tmp18_);
	temp_document = _tmp18_;
	g_object_set ((GtkWidget*) temp_document, "expand", TRUE, NULL);
	_tmp19_ = (GtkFrame*) gtk_frame_new ("terminal");
	g_object_ref_sink (_tmp19_);
	temp_terminal = _tmp19_;
	g_object_set ((GtkWidget*) temp_terminal, "expand", TRUE, NULL);
	_tmp20_ = (GtkFrame*) gtk_frame_new ("help");
	g_object_ref_sink (_tmp20_);
	temp_help = _tmp20_;
	g_object_set ((GtkWidget*) temp_help, "expand", TRUE, NULL);
	_tmp21_ = self->interface_tree;
	_tmp22_ = _tmp21_.viewport;
	gtk_container_add ((GtkContainer*) _tmp22_, (GtkWidget*) temp_tree);
	_tmp23_ = self->interface_document;
	_tmp24_ = _tmp23_.viewport;
	gtk_container_add ((GtkContainer*) _tmp24_, (GtkWidget*) temp_document);
	_tmp25_ = self->interface_terminal;
	_tmp26_ = _tmp25_.viewport;
	gtk_container_add ((GtkContainer*) _tmp26_, (GtkWidget*) temp_terminal);
	_tmp27_ = self->interface_help;
	_tmp28_ = _tmp27_.viewport;
	gtk_container_add ((GtkContainer*) _tmp28_, (GtkWidget*) temp_help);
	_tmp29_ = self->interface_grid;
	_tmp30_ = _g_object_ref0 (_tmp29_);
	result = _tmp30_;
	_g_object_unref0 (temp_help);
	_g_object_unref0 (temp_terminal);
	_g_object_unref0 (temp_document);
	_g_object_unref0 (temp_tree);
	return result;
}


gint incremental_main (gchar** args, int args_length1) {
	gint result = 0;
	Incremental* app = NULL;
	Incremental* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
	_tmp0_ = incremental_new ();
	app = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
	result = _tmp2_;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return incremental_main (argv, argc);
}


void incremental_svp_copy (const Incrementalsvp* self, Incrementalsvp* dest) {
	GtkScrolledWindow* _tmp0_ = NULL;
	GtkScrolledWindow* _tmp1_ = NULL;
	GtkViewport* _tmp2_ = NULL;
	GtkViewport* _tmp3_ = NULL;
	_tmp0_ = (*self).scroller;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 ((*dest).scroller);
	(*dest).scroller = _tmp1_;
	_tmp2_ = (*self).viewport;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_g_object_unref0 ((*dest).viewport);
	(*dest).viewport = _tmp3_;
}


void incremental_svp_destroy (Incrementalsvp* self) {
	_g_object_unref0 ((*self).scroller);
	_g_object_unref0 ((*self).viewport);
}


Incrementalsvp* incremental_svp_dup (const Incrementalsvp* self) {
	Incrementalsvp* dup;
	dup = g_new0 (Incrementalsvp, 1);
	incremental_svp_copy (self, dup);
	return dup;
}


void incremental_svp_free (Incrementalsvp* self) {
	incremental_svp_destroy (self);
	g_free (self);
}


GType incremental_svp_get_type (void) {
	static volatile gsize incremental_svp_type_id__volatile = 0;
	if (g_once_init_enter (&incremental_svp_type_id__volatile)) {
		GType incremental_svp_type_id;
		incremental_svp_type_id = g_boxed_type_register_static ("Incrementalsvp", (GBoxedCopyFunc) incremental_svp_dup, (GBoxedFreeFunc) incremental_svp_free);
		g_once_init_leave (&incremental_svp_type_id__volatile, incremental_svp_type_id);
	}
	return incremental_svp_type_id__volatile;
}


static void incremental_class_init (IncrementalClass * klass) {
	incremental_parent_class = g_type_class_peek_parent (klass);
	((GApplicationClass *) klass)->activate = incremental_real_activate;
	G_OBJECT_CLASS (klass)->finalize = incremental_finalize;
}


static void incremental_instance_init (Incremental * self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	_tmp0_ = g_strdup ("Incremental");
	self->AppName = _tmp0_;
	_tmp1_ = g_strdup ("0.1");
	self->Version = _tmp1_;
	_tmp2_ = g_strdup ("F10");
	self->hide_tree_accelerator = _tmp2_;
	_tmp3_ = g_strdup ("Toggle visibility of tree");
	self->hide_tree_tip = _tmp3_;
	_tmp4_ = g_strdup ("<ctrl><shift>n");
	self->append_node_accelerator = _tmp4_;
	_tmp5_ = g_strdup ("Append new node to tree");
	self->append_node_tip = _tmp5_;
	_tmp6_ = g_strdup ("<ctrl>n");
	self->file_new_accelerator = _tmp6_;
	_tmp7_ = g_strdup ("Create new empty document");
	self->file_new_tip = _tmp7_;
	_tmp8_ = g_strdup ("<ctrl>e");
	self->file_export_accelerator = _tmp8_;
	_tmp9_ = g_strdup ("Export to other format");
	self->file_export_tip = _tmp9_;
	_tmp10_ = g_strdup ("<ctrl>z");
	self->undo_accelerator = _tmp10_;
	_tmp11_ = g_strdup ("Undo last change");
	self->undo_tip = _tmp11_;
	_tmp12_ = g_strdup ("<ctrl>y");
	self->redo_accelerator = _tmp12_;
	_tmp13_ = g_strdup ("Redo last undone change");
	self->redo_tip = _tmp13_;
	_tmp14_ = g_strdup ("F12");
	self->hide_terminal_accelerator = _tmp14_;
	_tmp15_ = g_strdup ("Toggle visibility of terminal");
	self->hide_terminal_tip = _tmp15_;
	_tmp16_ = g_strdup ("F1");
	self->hide_help_accelerator = _tmp16_;
	_tmp17_ = g_strdup ("Toggle visibility of help browser");
	self->hide_help_tip = _tmp17_;
}


static void incremental_finalize (GObject* obj) {
	Incremental * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_INCREMENTAL, Incremental);
	_g_free0 (self->AppName);
	_g_free0 (self->Version);
	_g_object_unref0 (self->window);
	_g_object_unref0 (self->interface_grid);
	_g_object_unref0 (self->interface_tree_view);
	_g_object_unref0 (self->headerbar);
	_g_object_unref0 (self->hide_tree);
	_g_free0 (self->hide_tree_accelerator);
	_g_free0 (self->hide_tree_tip);
	_g_object_unref0 (self->append_node);
	_g_free0 (self->append_node_accelerator);
	_g_free0 (self->append_node_tip);
	_g_object_unref0 (self->file_box);
	_g_object_unref0 (self->file_new);
	_g_free0 (self->file_new_accelerator);
	_g_free0 (self->file_new_tip);
	_g_object_unref0 (self->file_select);
	_g_object_unref0 (self->file_export);
	_g_free0 (self->file_export_accelerator);
	_g_free0 (self->file_export_tip);
	_g_object_unref0 (self->undo);
	_g_free0 (self->undo_accelerator);
	_g_free0 (self->undo_tip);
	_g_object_unref0 (self->redo);
	_g_free0 (self->redo_accelerator);
	_g_free0 (self->redo_tip);
	_g_object_unref0 (self->hide_terminal);
	_g_free0 (self->hide_terminal_accelerator);
	_g_free0 (self->hide_terminal_tip);
	_g_object_unref0 (self->hide_help);
	_g_free0 (self->hide_help_accelerator);
	_g_free0 (self->hide_help_tip);
	incremental_svp_destroy (&self->interface_tree);
	incremental_svp_destroy (&self->interface_document);
	incremental_svp_destroy (&self->interface_help);
	incremental_svp_destroy (&self->interface_terminal);
	G_OBJECT_CLASS (incremental_parent_class)->finalize (obj);
}


GType incremental_get_type (void) {
	static volatile gsize incremental_type_id__volatile = 0;
	if (g_once_init_enter (&incremental_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (IncrementalClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) incremental_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Incremental), 0, (GInstanceInitFunc) incremental_instance_init, NULL };
		GType incremental_type_id;
		incremental_type_id = g_type_register_static (gtk_application_get_type (), "Incremental", &g_define_type_info, 0);
		g_once_init_leave (&incremental_type_id__volatile, incremental_type_id);
	}
	return incremental_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



